<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * SsoToken Model
 *
 * Represents single-use SSO tokens issued by the portal.
 * Tokens are temporary artifacts exchanged by the module frontend
 * for authenticated session context.
 *
 * Security Model:
 * - Tokens are generated by the portal only
 * - Each token is cryptographically signed
 * - Tokens have short expiration (5 minutes)
 * - Tokens are single-use (marked as exchanged after use)
 * - Tokens contain portal-signed user identity claim
 * - Module validates signature using portal's public key
 *
 * Lifecycle:
 * 1. Portal generates token with user identity + signature
 * 2. Portal sends token to module iframe (via postMessage)
 * 3. Module iframe sends token to exchange endpoint
 * 4. Module validates token signature and expiration
 * 5. Module marks token as exchanged (used)
 * 6. Module creates session and returns user context
 * 7. Token is never used again (prevented by "exchanged_at")
 */
class SsoToken extends Model
{
    protected $table = 'sso_tokens';
    protected $primaryKey = 'token';
    public $incrementing = false;
    public $keyType = 'string';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'token',
        'sso_id',
        'sso_role',
        'sso_name',
        'sso_email',
        'portal_signature',
        'portal_issued_at',
        'exchanged_at',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'portal_issued_at' => 'datetime',
        'exchanged_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Boot the model and add global scopes.
     */
    protected static function boot()
    {
        parent::boot();
        // Automatically set timestamps on token creation
    }

    /**
     * Check if token is valid (not expired, not exchanged, signature valid).
     *
     * @return bool
     */
    public function isValid(): bool
    {
        // Token already exchanged
        if ($this->exchanged_at !== null) {
            return false;
        }

        // Token expired (5-minute window from portal issue time)
        if ($this->portal_issued_at && now()->diffInMinutes($this->portal_issued_at) > 5) {
            return false;
        }

        // Portal signature is required and must not be empty
        if (empty($this->portal_signature)) {
            return false;
        }

        return true;
    }

    /**
     * Mark token as exchanged (single-use enforcement).
     *
     * @return void
     */
    public function markExchanged(): void
    {
        $this->update(['exchanged_at' => now()]);
    }

    /**
     * Validate portal signature on token.
     *
     * Uses portal's public key to verify the signature.
     * Ensures token was genuinely issued by portal and not tampered with.
     *
     * @param string $portalPublicKey The portal's public key (from config or fetched from portal)
     * @return bool
     */
    public function validateSignature(string $portalPublicKey): bool
    {
        try {
            $payload = json_encode([
                'sso_id' => $this->sso_id,
                'sso_role' => $this->sso_role,
                'sso_name' => $this->sso_name,
                'sso_email' => $this->sso_email,
                'portal_issued_at' => $this->portal_issued_at->toIso8601String(),
            ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

            return openssl_verify(
                $payload,
                base64_decode($this->portal_signature),
                $portalPublicKey,
                OPENSSL_ALGO_SHA256
            ) === 1;
        } catch (\Exception $e) {
            \Log::warning('[SSO] Signature validation error', [
                'token' => substr($this->token, 0, 8),
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    /**
     * Get a valid token by token string.
     *
     * @param string $tokenString
     * @return static|null
     */
    public static function findValid(string $tokenString): ?self
    {
        $token = self::where('token', $tokenString)->first();

        if ($token && $token->isValid()) {
            return $token;
        }

        return null;
    }

    /**
     * Clean up expired tokens (older than 10 minutes).
     *
     * @return int Number of tokens deleted
     */
    public static function cleanupExpired(): int
    {
        return self::where('portal_issued_at', '<', now()->subMinutes(10))->delete();
    }
}
